version: "3.5"
services:
  account-service:
    image: luongtx/account-service
    container_name: account-service
    ports:
      - "2222:2222"
    links:
      - discovery-service
    build:
      context: ./account-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

  customer-service:
    image: luongtx/customer-service
    container_name: customer-service
    ports:
      - "3333:3333"
    links:
      - discovery-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

  discovery-service:
    image: luongtx/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
